name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: docker build -t $DOCKER_IMAGE:latest .
        env:
          DOCKER_IMAGE: ${{secrets.DOCKER_IMAGE}}

      - name: Login
        run: echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        env:
          DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Push
        run: docker push $DOCKER_IMAGE:latest
        env:
          DOCKER_IMAGE: ${{secrets.DOCKER_IMAGE}}
